### ISSUE TITLE
Typings for ES7

### ISSUE THREAD

**Issue by drager** [typings/registry#121]
Would be nice to get some typings for features in ES7 and late stages of other proposed language extensions.

Thanks.

**Comment by blakeembrey** [comment]
What does this look like or mean? Can you share a reference or example so I can grok what you're after?

**Comment by drager** [comment]
Sorry for late answer, what I meant were typings for features like Object.values, Object.entries etc.

Example of typing:
```typescript
interface Object {
  entries(object: Object): Array<[string, any]>;
  values(object: Object): Array<any>;
}
```

**Comment by louy** [comment]
I think this should probably exist in something like **lib.es7.d.ts** in typescript core, or in a polyfill library's typings.

**Comment by louy** [comment]
Something like this one: https://github.com/es-shims/es7-shim

**Comment by johnnyreilly** [comment]
These sorts of things will typically ship with TypeScript itself in the form of lib.d.ts. There's also core-js (typings on DT at present) if you're shimming features.

**Comment by felixfbecker** [comment]
Closing in favor of `lib.es7.d.ts` or the typings that actually _provide_ these methods, like `core-js`.
