### ISSUE TITLE
Typings for Firebase

### ISSUE THREAD

**Issue by rolandjitsu** [typings/registry#123]
Not sure where to submit this, since TSD is being deprecated. But it looks like the DT typings for Firebase are a little outdated.

Some of the methods return promises now.

**Comment by dstauffer** [comment]
:+1:

**Comment by a8775** [comment]
+1

**Comment by warner-pinz** [comment]
+1

**Comment by mariommoreno** [comment]
+1

FirebaseAuthData only has `google?: FirebaseAuthDataGoogle;`
What about facebook, twitter and github?

**Comment by senayar** [comment]
+1

**Comment by paulogr** [comment]
+1

**Comment by jeaber** [comment]
+2

**Comment by aaronklaser** [comment]
+3

**Comment by wangbourne** [comment]
is it for firebase3.0? as far as I know, firebase has experienced a big upgrade during Google IO 2016.

**Comment by Epotignano** [comment]
+100

**Comment by aaronklaser** [comment]
So a work around is to set up all the Firebase config in the index file just as the documentation says. Then at the top of all your typescripts add declare var firebase: any;

**Comment by blakeembrey** [comment]
Yes, you can always use `any`. We also have a polyfill for the `any` behaviour - you can do `typings install firebase=common~any --save` to install the polyfill.

**Comment by jlsuarezs** [comment]
Try this one:
https://github.com/angular/angularfire2/tree/master/manual_typings/firebase3

**Comment by unional** [comment]
@jlsuarezs I created a repo based on your file. I'm not familiar with `firebase`. It seems to be quite different than the version in DT.
Would you like to take to take a look at it and if it is ok, it can be published to registry so you can add it in your `typings.json` instead of manually put it in your repo
https://github.com/typed-typings/npm-firebase

**Comment by Karasuni** [comment]
@unional Could you help me install your version of the typings? I can't seem to figure out how to properly include your registry in my ``typings.json``

**Comment by unional** [comment]
You can try it using `typings install github:typed-typings/npm-firebase`
If the typings is fine, then I can add it to the registry so you can `typings install firebase`

**Comment by 5amfung** [comment]
@unional Can you add to the registry?

**Comment by Karasuni** [comment]
Based on the same issue I'd also be interested in seeing a 3.0 update for angularfire

**Comment by unional** [comment]
> 3.0 update for angularfire

Please create a new typings request for it. Better yet, help create the typings 😉

**Comment by unional** [comment]
It is now in registry. Please file issue there https://github.com/typed-typings/npm-firebase/issues if something is missing or incorrect.
