### ISSUE TITLE
test fails on windows

### ISSUE THREAD

**Issue by joewashear007** [typings/registry#125]
Hey, love the project so far. I have tracked down an issues on windows with the test command.

### Details
* The output of `git diff --name-status HEAD~1` is `A       npm/sentiment.json`.
* The test tries to split apart `npm/sentiment` using the file system separator, which in window is `\`
* So the split never happens, cause the test script fail

### Fixes
* This [line](https://github.com/typings/registry/blob/master/test.js#L6]) seemed to be the issue. Replacing it with `var sep = "/"` makes it work.

**Comment by blakeembrey** [comment]
Awesome, thanks! I wasn't sure about the output on Windows, good to know I shouldn't be doing that.
