### ISSUE TITLE
We passed 100 typings for NPM alone!

### ISSUE THREAD

**Issue by blakeembrey** [typings/registry#147]
I think it's pretty cool. How long will it take to get to 200, 1000, 2000? Can it surpass DefinitelyTyped (that'll definitely help for future proofing with some things upcoming in TypeScript)? Just wanted to make this so people have visibility into progress so far. I'll be closing it right after :smile: 

Reference: https://api.typings.org/search?source=npm

**Comment by dsebastien** [comment]
+1
