### ISSUE TITLE
multiple versions of same package in same repo

### ISSUE THREAD

**Issue by louy** [typings/registry#171]
Is it possible to put multiple versions of the same package definitions in one repository without having to use tags/branches/commits. 

Something like using folders and `github:louy/typed-package/v0.1.0#COMMIT`.

**Comment by blakeembrey** [comment]
Yes.

**Comment by unional** [comment]
Will `/v0.1.0` be a folder contains `typings.json`? It is needed along with `.d.ts` if there are dependencies involved.

**Comment by blakeembrey** [comment]
Yes. You can always point to a location with either a `typings.json` or an entry `.d.ts` (that's how DefinitelyTyped is supported).

**Comment by louy** [comment]
Cool. Yeah it will be a folder. I was thinking about giving node typings a go.
