### ISSUE TITLE
gulp-tslint

### ISSUE THREAD

**Issue by unional** [typings/registry#178]

**Comment by MrHen** [comment]
gulp-tslint has an [`index.d.ts`](https://github.com/panuhorsmalahti/gulp-tslint/blob/master/index.d.ts) in its published code which is [automatically detected](http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html). I just tested this out locally and it works as advertised.

What else is needed?

**Comment by unional** [comment]
👍
