### ISSUE TITLE
Coding style for authoring typings (with tslint help)

### ISSUE THREAD

**Issue by unional** [typings/registry#195]
Link to: https://github.com/typings/typings/issues/314

Would like to get input from everyone. Please join the discussion there. Thanks.

**Comment by blakeembrey** [comment]
@unional Been using this lately, it's nice 😄 For my own code, I use `tslint-config-standard` (you know, no semicolons, etc) but for definitions I try to use your `typings` config which enforces semicolons and other consistencies with typical definition authoring.

I wonder if there's any rules for ending interfaces with commas vs semicolons, etc?

By the way, I'm going to close this issue and add the repo to the README here.

**Comment by unional** [comment]
:)  I think they don't have such rule any time soon: https://github.com/palantir/tslint/issues/960
