### ISSUE TITLE
search and installed package are not the similar version

### ISSUE THREAD

**Issue by tfiwm** [typings/registry#204]
Hi,

i searched for angularfire with
```
typings search angularfire --ambient
```
and receive this
NAME        SOURCE HOMEPAGE               DESCRIPTION UPDATED                  VERSIONS
angularfire dt     http://angularfire.com             2015-05-27T05:17:28.000Z 14  

after installation i  have an older version :(
```
"angularfire": "registry:dt/angularfire#1.6.4+20141105163827",
```
any idea what my mistake is?

**Comment by blakeembrey** [comment]
Since this isn't an issue with the registry, I'm going to close the issue and move it somewhere it can be tracked.

**Comment by tfiwm** [comment]
;) Thx!

**Comment by blakeembrey** [comment]
@tfiwm The core issue you had here was fixes also, you can install without issue :+1: The greater issue of versioning and DT is being tracked.
