### ISSUE TITLE
Expand registry entry details

### ISSUE THREAD

**Issue by blakeembrey** [typings/registry#21]
From https://github.com/typings/typings/issues/49, the registry should support extra information. Currently this is defined in the schema: https://github.com/typings/registry/blob/master/schema.json. New support should look like:

```
{
  "versions": {
    "2.0.0": [
      "github:foo/bar#commitish",
      {
        "compiler": "1.5.2", // Maybe it should specify the range or just imply greater than? E.g. "> 1.5.2".
        "location": "github:foo/bar-legacy#commitish",
        "description": "This is a legacy definition..."
      }
    ]
  }
}
```

Good time to think about other fields that might eventually need to be added too.

**Comment by samvloeberghs** [comment]
What's the exact use of the compiler option?

Maybe a reference to the website of the project or official documentation?
Those might also be subject to change on version updates. A good example of this is the zurb documentation. Perhaps this can be extracted automagically.
```
{
  "versions": {
      "6.1.x": [
      "github:foo/bar#commitish",
      {
        "compiler": "1.5.2", // Maybe it should specify the range or just imply greater than? E.g. "> 1.5.2".
        "location": "github:foo/bar-legacy#commitish",
        "description": "This is the current definition...",
        "docs": "http://foundation.zurb.com/sites/docs/"
      }
    ]
    "5.5.3": [
      "github:foo/bar#commitish",
      {
        "compiler": "1.5.2", // Maybe it should specify the range or just imply greater than? E.g. "> 1.5.2".
        "location": "github:foo/bar-legacy#commitish",
        "description": "This is a legacy definition...",
        "docs": "http://foundation.zurb.com/sites/docs/v/5.5.3/"
      }
    ]
  }
}
```
Grtz!

**Comment by blakeembrey** [comment]
> What's the exact use of the compiler option?

The compiler option is the lowest compatible TypeScript compiler. For example, some things won't compile on newer TypeScript versions because there's a new feature added - union types, string literals, etc.

> Maybe a reference to the website of the project or official documentation?

Absolutely, I started using the "homepage" option in the API (I expanded the API support before actually expanding the registry info). E.g. https://api.typings.org/search?name=jquery

One thing I'm still not sure of though, is whether this information should actually be here. I'm kind of leaning toward it being in the `typings.json` files and using the registry API to resolve this information. One reason it was important to be here initially was that no API existed, but that's no longer the case. I'll give some thought on it and probably make these updates over the weekend (resolving `homepage`, `authors`, `compiler`, etc) from the actual `typings.json` file.

**Comment by blakeembrey** [comment]
Latest thought: move all fields into `typings.json` and resolve `typings.json` information in the API (maybe routinely for health checking). However, since multiple typings might be published by different or the same authors there needs to be a way to specify an array still and associate identities to each addition. Perhaps tags are required when using more than one entry? Or maybe an `author` field? It'd be good to be able to publish updates via the CLI, so there needs to be some support for that in an easy way (`typings publish --tag v1`).

Otherwise I forget the tag option and I make updates override the existing entry for the version, or allow users to specify which one to override. GitHub repos are easy to associate updates with.
