### ISSUE TITLE
Jasmine done.fail callback

### ISSUE THREAD

**Issue by tpluscode** [typings/registry#311]
Hi. I've installed jasmine typings saved as ambient and it works great in my tests. The nuisance is with async tests where I pass `done.fail` to promise catch

``` js
if('should use done.fail', done => {

   promiseMeSomething()
      .then(outcome => {
         expect(outcome).toBe(true);
         done();
      })
      .catch(done.fail);
});
```

It works fine, but Webstorm complains saying *Unresolved variable fail*. Is there a good way around that?

**Comment by blakeembrey** [comment]
I don't use Webstorm, I know they use a custom implementation which has a lot of bugs in TypeScript. You'll be better off asking somewhere like StackOverflow.

**Comment by unional** [comment]
AFAIK, webstorm gets typings in two ways: their internal lib and DefinitelyTyped.

You have two options:
1. Open a PR on DT to fix `done.fail`
2. To this:
```ts
...
.catch((done as any).fail)
```

**Comment by blakeembrey** [comment]
@unional `done.fail` seems correct on DefinitelyTyped.

**Comment by unional** [comment]
Ok. Just check it out myself on phpStorm. It does download typings for 2.2. ANd the `done.fail` is indeed there.
So yeah, you need to file issue to Jetbrains.
