### ISSUE TITLE
Link to Microsoft AJAX defintion broken

### ISSUE THREAD

**Issue by DmytroLapshyn** [typings/registry#317]
Currently the link in the public registry points to an MSDN web page, while I guess the correct link would be https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/microsoft-ajax/microsoft.ajax.d.ts

**Comment by blakeembrey** [comment]
@DmytroLapshyn Can you provide more information with issues, I can't tell what you're referring to. Can you link me to the link you say is wrong?

**Comment by DmytroLapshyn** [comment]
Sure. If I do

`typings search microsoft.ajax`

I get

```
Viewing 1 of 1

NAME           SOURCE HOMEPAGE
      DESCRIPTION UPDATED
microsoft.ajax dt     http://msdn.microsoft.com/en-us/library/ee341002(v=vs.100).aspx             2016-03-17T12:06:54.000Z
```

where http://msdn.microsoft.com/... is obviously a wrong link that does not point to an actual repository containing the TypeScript definition file.

**Comment by blakeembrey** [comment]
It's not meant to and never has. It points to the homepage of the library.

**Comment by blakeembrey** [comment]
If you want to see all the versions and locations, you can run `typings view 'dt!microsoft.ajax' --versions`.

**Comment by DmytroLapshyn** [comment]
I did, and got

`typings ERR! message https://api.typings.org/entries/%27dt/microsoft.ajax%27/versions responded with 404, expected it to equal 200`

**Comment by blakeembrey** [comment]
@DmytroLapshyn If you're not in a Unix (looks like you're on Windows) please remove the quotes. Those are being sent in the URL above which is the cause of the 404.

**Comment by DmytroLapshyn** [comment]
That worked, thanks!
