### ISSUE TITLE
Difference between ambient and npm folders ?

### ISSUE THREAD

**Issue by koalabz** [typings/registry#32]
Hi @blakeembrey , 

I have just finished a [typed-electron](http://github.com/koalabz/typed-electron) module that support currently 2 versions 
```json
{
  "versions": {
    "0.35.4": "github:koalabz/typed-electron/electron.d.ts#c597a7362eb4605ad737217a19b701d4cf2bc80a",
    "0.36.0": "github:koalabz/typed-electron/electron.d.ts#2689b1648190d6921496a3f94c0d4e1ecae2ef1f"
  }
}
```

but i don't understand where i need to create the `electron.json` file. In `ambient` or `npm`folder ?

**Comment by blakeembrey** [comment]
That's amazing! Thanks for your work :smile: It would go in the `ambient` folder since you've built a typing for an environment, not an NPM package. Basically, the folders are meant to represent mappings. I'll clear this up in the README ASAP, so please keep this issue open :+1: 

Just one brief comment about your typings. I'd switch the `import` to remove the `.d.ts`, TypeScript will resolve that automatically using it's own import resolution.

**Comment by koalabz** [comment]
:+1: 

Another question: what do you think about letting each developer maintaining there own versions mapping inside their own typings.json (for simplicity purpose) and registry only mapping name => repo only like jspm registry does actually [`registry.json`](https://github.com/jspm/registry/blob/master/registry.json)

```json
{
  "name": "electron",
  "main": "electron.d.ts",
  "author": "koalabz <noreply@koalabz.com>",
  "description": "The TypeScript definition for electron.atom.io",
  ...
  "versions": {
    "0.35.4": "#c597a7362eb4605ad737217a19b701d4cf2bc80a",
    "0.36.0": "#2689b1648190d6921496a3f94c0d4e1ecae2ef1f"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/koalabz/typed-electron.git"
  },
   ...
  }
```

Pros: 
 * only one pull request needed the first time to map `project` => `repos`
 * easier for developer to maintain versions releases
 * `typings.json` didn't need extra 
```json
"ambientDependencies": {
    "node": "github:DefinitelyTyped/DefinitelyTyped/node/node.d.ts#5cb07b53719466b27cb32f3eb2c7c3e22575ecda"
  }
```
declarations but only the essential like `package.json`does
```json
"ambientdependencies": {
    "electron": "^0.35.4"
 }
```

**Comment by unional** [comment]
Should the json be:
```json
{
  "versions": {
    "0.35.4": "github:koalabz/typed-electron#c597a7362eb4605ad737217a19b701d4cf2bc80a",
    "0.36.0": "github:koalabz/typed-electron#2689b1648190d6921496a3f94c0d4e1ecae2ef1f"
  }
}
```
It should point to the repo, where it can fine the `typings.json` to get its dependencies and other information.

**Comment by blakeembrey** [comment]
@unional Technically both work (just install the definition, that's how DefinitelyTyped support occurs), but `typings.json` is preferred since it can contain additional information.

**Comment by unional** [comment]
Yes. Is it the same as :
```sh
typings i file:<path to d.ts>
# vs
typings i file:<path to typings.json>
```

**Comment by blakeembrey** [comment]
> Is it the same

Yes.

**Comment by blakeembrey** [comment]
Close this, I've killed the ambient folder and created specific "ambient" folders.
