### ISSUE TITLE
Improve new PR template

### ISSUE THREAD

**Issue by blakeembrey** [typings/registry#330]
Should ask for a link to GitHub release (or a description of the changes we're merging). This way we can understand why the same version requires updating (if it does). We can also promote using versioning inside of our repos, since we only need a commit-ish (could be a tag or branch, but we could use tags). By tagging, we'd be able to use GitHub releases to say what we changed.

Also, I think the Typings URL is a good feature, but the source URL should be accessible from the Typings URL README. Maybe redundant to specify both?

**Comment by unional** [comment]
> but the source URL should be accessible from the Typings URL README

If follow the pattern we have or using `generator-typings`

**Comment by unional** [comment]
Also, could change the tone in 1st person instead. e.g.:
```
typing URL...
Here are the changes:
...
```

**Comment by blakeembrey** [comment]
> If follow the pattern we have

If it's not accessible, we should open an issue anyway. Someone landing on the typed repo will be quite confused otherwise.

**Comment by blakeembrey** [comment]
Sure! Even something minimal would be enough, I think. 

```md
**Typings URL:**

**Description of addition or changes:**

Thanks for contributing!
```
