### ISSUE TITLE
Typings for GraphQL

### ISSUE THREAD

**Issue by bkinsey808** [typings/registry#342]
https://github.com/facebook/graphql

**Comment by calebmer** [comment]
There is [this](https://github.com/nitintutlani/typed-graphql) project. How can it be added to the registry?

**Comment by blakeembrey** [comment]
You'd need to make a PR for it. There's instructions in the README.

**Comment by louy** [comment]
@nitintutlani

**Comment by bkinsey808** [comment]
Might be worth mentioning that @ahejlsberg mentioned here https://youtu.be/m-yGjhCquK4?t=7m45s that type definitions are moving toward npm instead of definitely typed. "Types are just packages". npm is a good package manager, so why do we need definitely typed? So how do we grab the type definitions from an npm package? Here is a link to some documentation. https://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

**Comment by blakeembrey** [comment]
@bkinsey808 You're conflating two different things. If you are a package author and want to support TypeScript, you should definitely be publishing the typings with your NPM module. However, that's unrelated to this discussion. There's an issue on TypeScript to refactor DefinitelyTyped into external module, merge the Typings registry and create a script for publishing to a `@types` namespace on NPM. However, that link is not related.

**Comment by louy** [comment]
I dislike the idea of having typings-only packages published to npm because it's not possible to override a published version, meaning that there will be some mismatches between the typing version and the actual node package version in case there's a bug in the typing file or something. But still that's a separate discussion.

**Comment by bkinsey808** [comment]
I'm not familiar enough with the technical details why a typings registry would be better or worse than just using npm for a standalone typings file (made by a third party and not the original library author). I just want something that works. And in this case, from what I can tell, it seems that we have an impasse. If I understand correctly @nitintutlani isn't interested in publishing in typings, but importing via npm should work just fine. What's the right solution here? I'm humble enough to say I don't have all the answers. I'm excited about both typescript and graphql and would like to see the community find a good solution.

**Comment by blakeembrey** [comment]
@louy Realistically it looks exactly like the Typings registry - you can't override here either, it would break everyone's clients. Instead we issue a new semver build version. I've talked with the TypeScript team through all of this, so I trust it'll end well.

I'm not following what you're talking about though @bkinsey808. Are you saying someone has written type definitions already? What does this have to do with DefinitelyTyped?

**Comment by bkinsey808** [comment]
@blakeembry, what I'm talking about is that this case it looks like @nitintutlani is not interested in publishing his graphql typings package to definitely typed. So what is the protocol here?

https://github.com/nitintutlani/typed-graphql/issues/6

**Comment by blakeembrey** [comment]
@bkinsey808 Typings has nothing to do with DefinitelyTyped. It's also in the wrong format for DefinitelyTyped. However, it's in the correct format for Typings already. You can actually submit a PR right now to add it, if you wanted.

**Comment by blakeembrey** [comment]
It turns out that was my first comment on this issue. It's still valid, you can just make a PR to add the pointer. That said, I've left a note on the issue you linked me (DefinitelyTyped != Typings). It's only been a day, some people aren't online all the time - give it some time for them to respond.

**Comment by calebmer** [comment]
PR opened at #472, I’m going to need some advice on next steps for the questions.
