### ISSUE TITLE
Hashed url

### ISSUE THREAD

**Issue by tomitrescak** [typings/registry#383]
Fantastic effort! Takes a bit more time to understand the process, some case studies would help here a bit or "standard workflows ...tutorials".

I pretty much understand most now, yet, I have a problem with understanding where do you obtain the hashed URL from? github:.....#.

Thanks!

**Comment by blakeembrey** [comment]
The hash is just a commit/tag/branch ("commitish", a reference in Git). So it's `github:<username>/<repo>[/<path>]#<commit>` (you can grab the commit from Git or the GitHub UI by clicking in the recent commits and copying the commit hash.

![image](https://cloud.githubusercontent.com/assets/1088987/14939687/e55d4610-0f06-11e6-9ec1-ef55521cc72a.png)

**Comment by blakeembrey** [comment]
After that, I usually just use the Github UI to create/edit a file and make the PR. Thankfully the registry workflow is really simple so I rarely need to actually open an editor here anyway.

**Comment by blakeembrey** [comment]
Closing as answered, since there's been no response 😄

**Comment by tomitrescak** [comment]
Noted, thanks a lot for your response!
