### ISSUE TITLE
Typings for Autobahn

### ISSUE THREAD

**Issue by CosticaPuntaru** [typings/registry#402]
package: https://www.npmjs.com/package/autobahn

definitions can be found at: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/autobahn/autobahn.d.ts

**Comment by CosticaPuntaru** [comment]
i don't get what i am doing wrong:

```
>typings search --name autobahn
Viewing 1 of 1

NAME     SOURCE HOMEPAGE               DESCRIPTION VERSIONS UPDATED
autobahn dt     http://autobahn.ws/js/             1        2016-03-17T12:06:54.000Z
```


```
>typings install --save autobahn
typings ERR! message Unable to find "autobahn" ("npm") in the registry. Did you want to try searching another source? Also, if you want contribute these typings, please help us: https://github.com/typings/registry
t
```

**Comment by blakeembrey** [comment]
@CosticaPuntaru Please read the README of Typings. Use `typings install 'dt!autobahn' --save --ambient` or just `typings install autobahn --save --ambient` (because `dt` is the default source for ambient installations). Without it, the default source is `npm` - as mentioned in the error.
