### ISSUE TITLE
Typings for sweetalert2

### ISSUE THREAD

**Issue by limonte** [typings/registry#404]
https://limonte.github.io/sweetalert2/

**Comment by blakeembrey** [comment]
Doesn't this already exist? Someone has contributed this already. See https://github.com/typings/registry/blob/master/npm/sweetalert2.json.

**Comment by limonte** [comment]
I'm not sure how exactly works Typings. 

What I want to see in results is: https://github.com/limonte/sweetalert2
NPM link https://www.npmjs.com/package/sweetalert2 is also good, but it's not a main plugin page.
 
![pteg3hd](https://cloud.githubusercontent.com/assets/6059356/15154974/a7d61f4c-16e0-11e6-8907-f41d303b87af.png)

**Comment by blakeembrey** [comment]
@limonte Feel free to submit a PR. No one has actually cared to change that yet, you'll be the first 😄 You just need to add a `homepage` property to the file I linked above (here's the schema: https://github.com/typings/registry/blob/master/schema.json#L4-L6).

**Comment by limonte** [comment]
Thank you @blakeembrey for the support! I achieved my goal:

![mq97mzs](https://cloud.githubusercontent.com/assets/6059356/15185812/e1dea654-179a-11e6-9233-d9b2d7c45e04.png)

**Comment by blakeembrey** [comment]
Glad that worked immediately 😄 As I mentioned, you're the first to use it so I'm glad I didn't need to make changes to support it.
