### ISSUE TITLE
Confusion on repo naming

### ISSUE THREAD

**Issue by cyounkins** [typings/registry#407]
In the README it says "Initialize a new repository (usually typed-<package name> to differentiate from your other projects)"

But it looks like typed-debug was renamed to npm-debug? Lacking 'type' of any form in the name seems weird - just from the package name you can't tell what you're getting is just type definitions.

**Comment by blakeembrey** [comment]
It's a recommendation. You're welcome to do whatever you please yourself. It seems redundant for the organisation of `typed-typings` to also say `typed-` in the repo name, no?
