### ISSUE TITLE
Add dt item to sources

### ISSUE THREAD

**Issue by deni35** [typings/registry#426]
There https://github.com/typings/typings there is 9 sources.
But here https://github.com/typings/registry only 8 sources.

Add 9'th ```dt``` item.
Or to avoid duplication of information, remove this section and add link to https://github.com/typings/typings/blob/master/docs/registry.md Only complete this document.

Also make description of typings.json. It will be almost the same as registry docs. But it's needed for beginners.

**Comment by Fank** [comment]
No, because these address different informations:
https://github.com/typings/typings will show what prefix can be used to install typings
https://github.com/typings/registry will show the folder structure

**Comment by blakeembrey** [comment]
@deni35 I'm going to close this. The sources in the README here document the sources that are maintained by the registry. The information on Typings is all available sources. I don't see an elegant way to de-dupe this information and not make it confusing.

**Comment by blakeembrey** [comment]
What do you want for `typings.json`? It's documented in Typings, see https://github.com/typings/typings/blob/master/docs/faq.md#writing-typings-definitions (which links to a TypeScript definition of the up-to-date interface: https://github.com/typings/core/blob/master/src/interfaces/config.ts).
