### ISSUE TITLE
installing typings require failed in macOSX

### ISSUE THREAD

**Issue by MortezaAghili** [typings/registry#427]
I following a tutorial to 'use PouchDB for localStorage in ionic' and the author says i need run this command:

    typings install require --ambient --save

i know in version 1.0 of typings, ambient changed to global but when i run this command i get an error:

    sudo typings install require --global --save
    typings ERR! message Unable to find "require" ("npm") in the registry. Did you want to try searching another source? Also, if you want contribute these typings, please help us: https://github.com/typings/registry
    typings ERR! caused by https://api.typings.org/entries/npm/require/versions/latest responded with 404, expected it to equal 200

    typings ERR! cwd /Users/userName/Desktop/ionic-projects/ionic2-tutorial-pouchdb
    typings ERR! system Darwin 15.4.0
    typings ERR! command "/usr/local/bin/node" "/usr/local/bin/typings" "install" "require" "--global" "--save"
    typings ERR! node -v v4.4.4
    typings ERR! typings -v 1.0.4

    typings ERR! If you need help, you may report this error at:
    typings ERR!   <https://github.com/typings/typings/issues>

thanks

**Comment by Fank** [comment]
in <1.0 ambient flag means it will also search in dt, but now it doesn't.
If you want to install something you cant find, try the search command:
```
typings search require
Viewing 4 of 4

NAME                        SOURCE HOMEPAGE                                DESCRIPTION VERSIONS UPDATED                 
require                     dt     http://requirejs.org/                               1        2016-03-16T15:55:26.000Z
requirejs                   npm    https://www.npmjs.com/package/requirejs             1        2016-03-19T06:23:57.000Z
requirejs                   env                                                        1        2016-03-19T06:20:41.000Z
requirejs-domready/domready dt     https://github.com/requirejs/domReady               1        2016-03-16T15:55:26.000Z
```
So in this example you need to do:
```
sudo typings install dt~require --global --save
```
because the `require` typing is listed in `dt`

**Comment by Fank** [comment]
But as you may see, there are `env` typings which are prefered try to use these:
```
typings install env~requirejs --global --save
```

**Comment by blakeembrey** [comment]
@MortezaAghili Please read the README in Typings, it documents these changes: https://github.com/typings/typings.

**Comment by blakeembrey** [comment]
Thanks @Fank 😄
