### ISSUE TITLE
Bad typing for redux-thunk

### ISSUE THREAD

**Issue by zaytsevvla** [typings/registry#450]
I can't understand issue source: 
```typescript
/// <reference path="typings/index.d.ts" />

import { applyMiddleware } from 'redux';
import thunkMiddleware from 'redux-thunk';

let test = applyMiddleware();
let test2 = applyMiddleware(thunkMiddleware);
```

`tsc test.ts` tell `test.ts(7,29): error TS2304: Cannot find name 'thunkMiddleware'.`

how to reproduce:
```bash
npm init
npm install typings redux redux-thunk
typings install redux-thunk
```

**Comment by unional** [comment]
You can file issue directly in that repo. Look into the `npm/radux-thunk.json` to find out where is the repo

**Comment by unional** [comment]
Actually, it is an regression:
https://github.com/typings/typings/issues/525

**Comment by blakeembrey** [comment]
Closing in favour of https://github.com/typings/typings/issues/525. Unfortunately there's nothing Typings can do right now - my hands are tied on support and TypeScript really needs to be fixing this bug.
