### ISSUE TITLE
installing foundation-sites gives error

### ISSUE THREAD

**Issue by samvloeberghs** [typings/registry#46]
Hello,

So i've tried to install the foundation-sites typings I've added recently into a project.
It gives me this error, and I don't quite understand it :)

```
C:\Users\svloeberghs\Documents\angular2-webpack-starter>typings install foundation-sites
? Found typings for foundation-sites in multiple registries Ambient
Installing foundation-sites@6.1.1 (Ambient)...

typings ERR! message Attempted to compile "foundation-sites" as a dependency, but it contains ambient modules ("Foundation"). Did you w
ant to specify "--ambient" instead?

typings ERR! cwd C:\Users\svloeberghs\Documents\angular2-webpack-starter
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\svloeberghs\\AppData\\Roaming\\npm\\node_modules\\typings\\dist\
\bin\\typings-install.js" "foundation-sites"
typings ERR! node -v v4.2.1
typings ERR! typings -v 0.5.1

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

I did specify ambient in the choice it gave me.
Any thoughts on this?

Grtz

**Comment by blakeembrey** [comment]
Apologies for this. I'll have to improve this UX and documentation. It's (trying) to say that you should use `typings install foundation-sites --ambient` since the dependency is ambient.

Side question about UX: Do you think install should search and prompt if it's ambient, or do you think it should search one or the other based on the flag? I'm leaning toward the latter myself. Feel free to not answer if the question doesn't make sense too :smile:

**Comment by basarat** [comment]
> Side question about UX: Do you think install should search and prompt if it's ambient, or do you think it should search one or the other based on the flag

`--ambient` : ambient only

`or the other based on the flag` : I couldn't see a flag there : https://github.com/typings/typings#flags perhaps `--module` :  module only 

`--auto` : try module and then fall back to trying ambient. This is the default.

I might be completely misunderstanding :rose: Admittedly I still haven't had a deep look at your great work (you set it up on atom-typescript and its worked as a charm :smile:)

**Comment by blakeembrey** [comment]
I ended up just making installation search using the `--ambient` flag - feel like it's a little less confusing for now since that's the same way it writes and saves to `typings.json`. So it's either ambient or not, and installation applies the same rules.

What was the `--module` flag you mention? The opposite of ambient?

**Comment by basarat** [comment]
> What was the --module flag you mention? The opposite of ambient?

Yup. I am assuming:

`--module foo`
```
export declare var someThing:any;
```

`--ambient foo`
```
declare var someThing:any;
```

**Comment by blakeembrey** [comment]
I'll have to pick your brain on what the flags mean to you, but the `--ambient` flag is currently a boolean. I use it to explicitly enable ambient declarations (I could implicitly support it, but since they aren't compatible I've tried to keep the modes distinct).

**Comment by basarat** [comment]
> I'll have to pick your brain on what the flags mean to you

I would like that. I read the original blog post by you : http://angularclass.com/the-state-of-typescript-packages/ :rose: It gave the why (which I totally get). The how for *usage* is covered here : https://github.com/typings/typings 

I suspect there is a how for creation missing here : https://github.com/typings/registry Also I suspect you already have automated magic already working for all them DT defs. 

I might be wrong on various things here. Would love to pick your brain :rose:

**Comment by blakeembrey** [comment]
> Also I suspect you already have automated magic already working for all them DT defs.

I published and have deployed an API, available at https://github.com/typings/api. It's basically just indexing DT and this registry every hour.

> I suspect there is a how for creation missing here : https://github.com/typings/registry

Most definitely, there's some guides missing. I have a couple of issues logged for improving that, but can certainly use help (https://github.com/typings/typings/issues/70, https://github.com/typings/typings/issues/57).

If you want to set aside some time and chat, that would definitely be cool - my email is public on my profile, feel free to shoot me an email.

**Comment by samvloeberghs** [comment]
just to wrap up that `--ambient` works perfect!
