### ISSUE TITLE
Typings for Passport.js

### ISSUE THREAD

**Issue by blakeembrey** [typings/registry#479]
* `passport`
* `passport-twitter`
* `passport-google-oauth`

I found the DefinitelyTyped definitions _mostly_ alright, but run into a few situations where none of the overloads have been defined.

**Comment by seriema** [comment]
Can I add [passport-fitbit-oauth2](https://github.com/thegameofcode/passport-fitbit-oauth2) to the list? It's linked from [jaredhanson/passport-fitbit](https://github.com/jaredhanson/passport-fitbit) which is now deprecated.

**Comment by blakeembrey** [comment]
Finally getting to this, will continue on it tomorrow. I just typed Fitbit in https://github.com/typings/registry/pull/855 but it'll probably be more useful once I get around to the rest.

**Comment by blakeembrey** [comment]
Closed with https://github.com/typings/registry/pull/865.
