### ISSUE TITLE
Typings for Notification API (Web Workers)

### ISSUE THREAD

**Issue by heruan** [typings/registry#551]
https://developer.mozilla.org/en/docs/Web/API/notification

**Comment by heruan** [comment]
Since it's a core browser interface, it should be added to the TS libs: https://github.com/Microsoft/TypeScript/issues/3111

**Comment by blakeembrey** [comment]
It definitely should be in the long run. There's definitely no problem adding it to the registry until then though, I don't think. Think of Typings as one giant polyfill 😄
