### ISSUE TITLE
Typings of svg.js delievered with package now

### ISSUE THREAD

**Issue by Fuzzyma** [typings/registry#574]
The svg.js typings now get served with the package. When you search for svg.js typings with `typings search svgjs` you still get the old (registered?) typings.
How do I change that?

**Comment by unional** [comment]
That's good news. To remove it from search, just create a PR to delete the json file form this registry.

**Comment by Fuzzyma** [comment]
I would but I cant find it :D

**Comment by blakeembrey** [comment]
@Fuzzyma They are provided by DefinitelyTyped. Typings from DefinitelyTyped come from https://github.com/DefinitelyTyped/DefinitelyTyped. While you're at it, `moment` should also be remove - as well as any `*-case` module of mine. Feel free to link back to here 😄
