### ISSUE TITLE
rx-lite downloading wrong file

### ISSUE THREAD

**Issue by OliverJAsh** [typings/registry#613]
We download https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/rx/rx-lite.d.ts when we should download https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/rx/rx.lite.d.ts. How can this be fixed?

**Comment by blakeembrey** [comment]
Can't be fixed in the registry. You can ask DefinitelyTyped to structure the files in a simpler way, it's really impossible to know which file to download automatically. If you want the other file, you can search for it using Typings - it seems it's under `rx.lite`.

**Comment by OliverJAsh** [comment]
Makes sense, thank you!
