### ISSUE TITLE
Typings for React Router appear to be broken

### ISSUE THREAD

**Issue by jpierson** [typings/registry#619]
Today I tried installing type definitions for react-router using the following command.

```
typings install react-router --save
```

Which yielded the output.

> typings WARN badlocation "github:andrew-w-ross/typings-history" is mutable and may change, consider specifying a commit hash
> typings INFO reference Stripped reference "https://raw.githubusercontent.com/typed-typings/npm-react-router/5d1691d5406392867926587830c2b20645eabd46/typings/main.d.ts" during installation from "react-router" (main)
> react-router
> └── history

It doesn't appear that the typings were installed at all by evidence of looking at the `typings/modules` directory however the typings.json file does contain the line under dependencies `"react-router": "registry:npm/react-router#2.4.0+20160628165748"`

Ultimately this manifests itself as an issue when building with `tsc` with the following errors.

> typings/modules/react-router/index.d.ts(172,77): error TS2503: Cannot find namespace 'JSX'.
> typings/modules/react-router/index.d.ts(205,35): error TS2503: Cannot find namespace 'JSX'.
> typings/modules/react-router/index.d.ts(890,73): error TS2503: Cannot find namespace 'JSX'.
> typings/modules/react-router/index.d.ts(890,101): error TS2503: Cannot find namespace 'JSX'.

Running the following command to specifically pull from Definitely Typed seems to have worked around my immediate issue.

```
typings install dt~react-router --save --global
```

**Comment by blakeembrey** [comment]
It looks like the type definition has installed fine, it just expected a global `JSX` namespace. This is definitely a bug, but not a Typings issue. Please log issues with definitions to the developers - https://github.com/typed-typings/npm-react-router.
