### ISSUE TITLE
Nightmare.js - TS2304: Cannot find name Buffer

### ISSUE THREAD

**Issue by RichardJECooke** [typings/registry#659]
Nightmare typings don't compile. (It has lots of ts-lint errors too :(

Screenshot of the problem:

![untitled](https://cloud.githubusercontent.com/assets/5468805/17292879/efa20b90-57ec-11e6-88f7-f9d597b4878c.png)

**Comment by unional** [comment]
Issue created on the repo. Please continue the discussion there.
🌷
