### ISSUE TITLE
Move typed-jsonwebtoken to types/

### ISSUE THREAD

**Issue by felixfbecker** [typings/registry#675]
There are outstanding issues and PRs at https://github.com/enriched/typed-jsonwebtoken and the author does not seem to respond. The typings seem to be copied from DT and are MIT, I would propose to make a new repo under types/npm-jsonwebtoken so the typings can evolve further.

**Comment by blakeembrey** [comment]
Sounds like a great idea 👍 Been meaning to do the same thing, using the same typings - you can also just fork and we'll continue working on it in @types.

**Comment by felixfbecker** [comment]
https://github.com/types/npm-jsonwebtoken
