### ISSUE TITLE
Request for review: superagent-promise

### ISSUE THREAD

**Issue by apeace** [typings/registry#693]
Hey there, I created typings for the superagent-promise library: lightsofapollo/superagent-promise#26

I'm wondering if anyone would have time to review it for me? It is my first time writing a type definitions file. The author has indicated that he'd be willing to merge into the package, which I think is great!

[This issue](https://github.com/typings/typings/issues/322) suggested that some @typings folks may be willing to help review.

**Comment by blakeembrey** [comment]
Absolutely! 👍 I'll take a quick look now 😄

**Comment by blakeembrey** [comment]
It's really unfortunate, but it turns out org notifications across org doesn't work 😦 Not sure if someone from @github could give guidance on how to better handle this?
