### ISSUE TITLE
Request for review - redux-persist

### ISSUE THREAD

**Issue by pellejacobs** [typings/registry#696]
I was trying to write down a simple declaration file for [redux-persist](https://github.com/rt2zz/redux-persist), but got stuck with a couple of issues and some help would be extremely appreciated 😄 

- The api exposes two modules: `redux-persist` and `redux-persist/constants`. I did not find any documentation on how to expose submodules, so I tried to base myself on [lodash's DT file](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/25b78b03bc815ea2d19b2e1a100988a8303f931e/lodash/lodash.d.ts), I think I failed: https://github.com/pellejacobs/typed-redux-persist/blob/master/index.d.ts#L66-L69

- I would like to import some types (eg. `Store`) from the redux package. However, `redux-persist` does not include `redux` in its dependencies, so I tried to install the [declaration file from the package](https://github.com/reactjs/redux/blob/master/index.d.ts) through typings, but I couldn't find it. I feel like I am missing something here, this should be possible no? 

For reference: here is the file as far as I got: https://github.com/pellejacobs/typed-redux-persist/blob/master/index.d.ts 

Cheers!

**Comment by felixfbecker** [comment]
For the submodule, just add a constants.d.ts file.

**Comment by blakeembrey** [comment]
For 2, it's possible to install but might just be worth using a `peerDependency` for now - we haven't really resolved how to do that appropriately, so either a `peerDependency` or do an `npm install redux` and then use `typings install npm:redux` instead.

**Comment by pellejacobs** [comment]
Great. I tried to finish the definition file, here is the PR: #698. 

I don't fully understand the difference between a peerDependency and a normal dependency, so I tried both. When I then installed my typings from my repo into another project, only the one with the dependency actually took the dependency over in the newly generated `typings/modules/redux-persist/index.d.ts` file. What is exactly the purpose of the peer dependencies in typings? It's not that well documented.

I put the constants into a separate file, but had to make it global to make the test work. However, it is not included when you run `typings i -S "github:pellejacobs/typed-redux-persist#master"`, you'd have to install it separately 😕 . 

Although having submodules is not that uncommon, I couldn't find any examples that actually defined a module with submodules. Take lodash eg. There is a declaration file for it in the types organisation (https://github.com/types/npm-lodash), but this one only supports importing from `lodash`, and not eg. from `lodash/map`. The DT declaration file, does, but of course, is global.

**Comment by felixfbecker** [comment]
@pellejacobs See https://github.com/louy/typed-sequelize/tree/master/4 for example, it massively uses "submodules".

**Comment by pellejacobs** [comment]
I think I finally got the hang of it 🎉  

Would you guys mind to have a look at the repo? It's my first declaration file, so there is probably some room for improvement. 

Just in general, I'd be nice to have these examples somewhere listed in the documentation. It's hard to find a proper example of every special case (submodules, dependencies, etc...).

**Comment by felixfbecker** [comment]
You don't need to `declare module Redux`, just export from the modules scope (besides that, `module` keyword for "internal modules" is deprecated now and has been replaced by `namespace`)

**Comment by unional** [comment]
Yup.
https://github.com/unional/typescript-guidelines/blob/master/pages/default/namespaces-and-modules.md

**Comment by pellejacobs** [comment]
Nice! Thanks guys 😎
