### ISSUE TITLE
Test suite does not run clean

### ISSUE THREAD

**Issue by pellejacobs** [typings/registry#707]
`npm run test-all` does not complete, as there are several records not longer up to date. Eg. `global/jacada-interact-extension.json` has a commit sha that doesn't exist, `npm/switchery.json` points to a global module, ...

I understand that you don't want the test suite to fail when you submit a new declaration file, just because someone deleted their repo, but the green build that you see now on CI kind of gives the wrong impression. 

A solution could be to just have a different build (`npm run test-all` instead of `npm test`) for the typings/registry master branch.

**Comment by blakeembrey** [comment]
Closed with https://github.com/typings/registry/commit/22677250689b1ae3f3d6fcbd82db40798a134d39. It's the only issue I did encounter, the rest seem to work.
