### ISSUE TITLE
RFC: typings for phoenix

### ISSUE THREAD

**Issue by akeating** [typings/registry#713]
https://github.com/akeating/typed-phoenix

I created typed definitions for phoenix framework and am considering contributing them to typings . 

The phoenix [lib](https://www.npmjs.com/package/phoenix) is written in es6. I rewrote it in Typescript and generated the definition (and a source) that is closely compatible with the original source. I plan to maintain this by modifying my Typescript source as Chris McCord's underlying lib changes.

Are there any obvious issues or changes I'll need to make to ensure compatibility with the Typings registry and ready the repo for a pr?

**Comment by blakeembrey** [comment]
It looks ok, but I'd recommend using it with `noImplicitAny` as I think a few people won't be able to use the current definition if they have that enabled.

**Comment by felixfbecker** [comment]
Rewriting the source in TS seems like a lot of effort 😲

**Comment by akeating** [comment]
@blakeembrey yeah we're ok as I used the following command-line to generate the definition:
```
tsc lib/phoenix.ts -d --noImplicitAny --noImplicitReturns
```

**Comment by akeating** [comment]
@felixfbecker I discovered hand-rolling the definition worked for minimal usage. Overall though the process seemed error-prone and time-consuming. I decided the tradeoff was worth it mainly because the  underlying lib was written in es6 which is not too far from Typescript with a little effort. The generation process gave me a fairly comprehensive baseline definition to improve, I learnt a lot about Typescript and I suspect the total time involved to be roughly equivalent.

**Comment by felixfbecker** [comment]
@akeating It probably was a good idea to copy the source and start from there if it is ES6. But I think it will be a pain if you want to keep the source up-to-date. I would remove the implementations and rename the files to .d.ts, it will be easier for long-term maintenance.

**Comment by akeating** [comment]
I suspect you're right about that. It should be easier to look for signature changes than diffing and refactoring the source.

**Comment by akeating** [comment]
One question I do have though. I marked many properties as _private_ which had the consequence of removing the typing from the generated definition. What are the definition best practices when it comes to access modifiers? The definition does lose a lot of information by using _private_ but on the other hand access modifiers clarify the author's intention. This distinction is perhaps less important in javascript. Given the underlying source is javascript, I am inclined to remove the _private_ access modifiers so the resulting definition has a richer set of typings.

**Comment by felixfbecker** [comment]
`private` means the user should not use it, typically what is prefixed with an underscore in JS. It can be beneficial to include it in the typings because it prevents a user from overriding a private property without noticing.

**Comment by akeating** [comment]
There are some inconsistencies in the underlying source, so I have removed access modifiers pending comment from the author. In the meantime I have removed my typescript source and prepared #715.
