### ISSUE TITLE
Typings for monk

### ISSUE THREAD

**Issue by sfali23** [typings/registry#723]
Hi There,

I have created typings for "[monk](https://github.com/sfali23/typings-monk)", I would like to add this.

I have forked from typings/registry and added it to registry as well ([monk.json](https://github.com/sfali23/registry/blob/master/npm/monk.json)). When I am trying to run:
           `npm run test`
I am getting:
`TypingsError: Attempted to compile "monk" as an external module, but it looks like a global module. You'll need to enable the global option to continue.`

Is this the correct way to contribute?

Regards,

Farhan

**Comment by felixfbecker** [comment]
You should remove the `declare module 'monk'`

**Comment by sfali23** [comment]
Thanks for quick reply, I made it work. I am using target es6 when compiling, is it possible to have different implementation based on target.

Reason I am asking is that I am using es6 Promise if I use target es6 then I don't have to import Promise but for target es5 I need to import dependency.

Thanks in advance.

**Comment by felixfbecker** [comment]
These are the typings for the NPM package `mongodb`, right? Then your repo should be named `typed-mongodb` and the JSON file `npm/mongodb.json`.

**Comment by felixfbecker** [comment]
What is the purpose of this namespace? https://github.com/sfali23/typings-monk/blob/master/monk.d.ts#L68

**Comment by felixfbecker** [comment]
And no, different deps for different targets are not possible. Typically definitions add a dependency on `es6-promise`.

**Comment by sfali23** [comment]
This is for monk, which is Promise based API for MongoDB, I have updated the README to reflect correct package. Also changed definition to use `es6-promise`.

As for namespace that will be entry point to connect to DB.

Regards,

Farhan

**Comment by felixfbecker** [comment]
Looking at the README for monk, it seems like monk actually just `module.exports` a function? Is that correct?

https://github.com/Automattic/monk

**Comment by sfali23** [comment]
Actual work is done via Manager and Collection, in monk.js these modules gets exported.

**Comment by felixfbecker** [comment]
https://github.com/Automattic/monk/blob/master/lib/monk.js#L6

**Comment by felixfbecker** [comment]
The manager should be `export =`

**Comment by sfali23** [comment]
I think that's the entry point, which gives access to collection

**Comment by felixfbecker** [comment]
Yeah. It should be exported with `export =`.

**Comment by sfali23** [comment]
Thanks for your feedback and help.

**Comment by felixfbecker** [comment]
No problem :)
