### ISSUE TITLE
How to fix bluebird.d.ts Duplicate identifier 'Promise' error?

### ISSUE THREAD

**Issue by unional** [typings/registry#73]
When I run `tsc -d` on my project that use `bluebird` (i.e. installing typed file with `typings install bluebird --ambient`), I run into this:

typings/browser/ambient/bluebird/bluebird.d.ts(21,15): error TS2300: Duplicate identifier 'Promise'.
typings/browser/ambient/bluebird/bluebird.d.ts(637,16): error TS2300: Duplicate identifier 'Promise'.

The corresponding lines:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ffceea9dd124d277c4597c7bd12930666ec074c5/bluebird/bluebird.d.ts#L19
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ffceea9dd124d277c4597c7bd12930666ec074c5/bluebird/bluebird.d.ts#L629

What should I do to:
* fix it
* move it to `typings/registry`

**Comment by unional** [comment]
Similar issue with `core-js`:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7590f7725e5af7191a075700a70e4408b4f9cd45/core-js/core-js.d.ts#L754
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7590f7725e5af7191a075700a70e4408b4f9cd45/core-js/core-js.d.ts#L831

**Comment by blakeembrey** [comment]
So this is the primary reason to start fixing definitions and making them external module definitions. I won't be fixing definitions in DefinitelyTyped since it's all subjective there, but you could create a typings definition and add it to the registry for Typings.

For `core-js`, there may be a need for feature flags or such in the future. For now, I think docs might suffice but I need a better way to warn post-install. Definitely a suggestion I'll be adding to the backlog.

**Comment by unional** [comment]
Yes I can create one into registry, but I need to know how do I fix it. Need some guidance from you. :)

**Comment by blakeembrey** [comment]
@unional Luckily, this one is very simple. Just change the last three lines (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ffceea9dd124d277c4597c7bd12930666ec074c5/bluebird/bluebird.d.ts#L744-L746):

```ts
declare module 'bluebird' {
	export = Promise;
}
```

To a top level export (therefore making it an external module and not ambient).

```ts
export = Promise;
```

**Comment by unional** [comment]
`core-js` would be much more complicate I assume. It has many `declare module ... export =` for each sub component.

**Comment by unional** [comment]
Need to get these two fixed and my internal project will start to work amaze

**Comment by unional** [comment]
It started working! Hooray!!!
