### ISSUE TITLE
How to prevent deprecated typings?

### ISSUE THREAD

**Issue by bennyn** [typings/registry#745]
In my `typings.json` file I have this:
```json
{
  "globalDependencies": {
    "node": "registry:dt/node#6.0.0+20160621231320"
  }
}
```

When executing `typings install` I get the following error:
> typings WARN deprecated 2016-08-31: "registry:dt/node#6.0.0+20160621231320" is deprecated (updated, replaced or removed)

How can I prevent typings to get outdated? Can I lock them to a specific version like `registry:dt/node#6.0.0`?

**Comment by blakeembrey** [comment]
You can, but you should not. That would mean they could break at anytime if someone makes a breaking change in 6.0. It's only information, it's up to you if you want to update them right now. If you really desire to do it, I'd check the docs - specifying a version is done with `@` (but I've never used it myself).
