### ISSUE TITLE
Port toolings type file with higher priority?

### ISSUE THREAD

**Issue by unional** [typings/registry#75]
Propose to port tools such as gulp, mocha, jasmine, chai, etc over to typings first.

Currently, without porting them over, `typings i -D ...` would cause unnecessary compile error because `browser.d.ts` and `main.d.ts` include dev dependencies just like regular dependencies.

So `tsc` will fail with error such as:
```sh
typings/browser/ambient/gulp/gulp.d.ts(10,35): error TS2307: Cannot find module 'orchestrator'.
typings/browser/ambient/gulp/gulp.d.ts(50,31): error TS2503: Cannot find namespace 'NodeJS'.
typings/browser/ambient/gulp/gulp.d.ts(60,66): error TS2503: Cannot find namespace 'NodeJS'.
typings/browser/ambient/gulp/gulp.d.ts(67,68): error TS2503: Cannot find namespace 'NodeJS'.
typings/browser/ambient/gulp/gulp.d.ts(75,85): error TS2503: Cannot find namespace 'NodeJS'.
typings/browser/ambient/gulp/gulp.d.ts(83,87): error TS2503: Cannot find namespace 'NodeJS'.
typings/browser/ambient/gulp/gulp.d.ts(95,80): error TS2503: Cannot find namespace 'NodeJS'.
typings/browser/ambient/gulp/gulp.d.ts(104,56): error TS2503: Cannot find namespace 'NodeJS'.
```
because of `typings i -D gulp --ambient`, while without that it is building fine.

**Comment by blakeembrey** [comment]
Would you mind making typings requests for each implementation you want to see? That way tasks can be closed when they're done (right now this is open ended with "etc"). It's ok to have a dozen requests open.

The other side is, I think Gulp is the big one to change here. The other ones you mentioned are primary creating their own test environments too, which I believe is mostly ok in their current forms.

**Comment by unional** [comment]
Sure, just want to go over the idea with you in case you have a different opinion.

**Comment by blakeembrey** [comment]
Nope, definitely agree. I just have a lot on my plate already and need others to pitch in for the actual definitions :+1:

**Comment by unional** [comment]
Adding. And I'm adding those that I'm using myself. :smile:

**Comment by blakeembrey** [comment]
Thank you :smile:
