### ISSUE TITLE
re-exporting module / namespace

### ISSUE THREAD

**Issue by sfali23** [typings/registry#755]
Hi,

There are examples to re-export interface or class from one namespace to another namespace, how do you re-export entire namespace:

Consider following example:

file - `my_decl1.d.ts`:

```
declare namespace my_decl1 {

   // decelerations here
}

export = my_decl1;
```

file - `my_decl2.d.ts`:

```
declare namespace my_decl2 {

   // decelerations here

  // re-export my_decl1
}

export = my_decl2;
```
 
Regards,

Farhan

**Comment by blakeembrey** [comment]
Can you provide more information on why/how? You probably should be writing code like this. If you're writing a declaration, can you use ES6-style? That would support `export * from './1'`.

**Comment by felixfbecker** [comment]
This may help you:

https://github.com/louy/typed-sequelize/blob/master/4/lib/sequelize.d.ts#L5
https://github.com/louy/typed-sequelize/blob/master/4/lib/sequelize.d.ts#L1261

**Comment by sfali23** [comment]
Thanks, this exactly what I was looking for
