### ISSUE TITLE
Add bluebird to npm or ambient?

### ISSUE THREAD

**Issue by unional** [typings/registry#76]
My guts tells me to put in under npm, but it touches the environment....

**Comment by blakeembrey** [comment]
I don't believe it does, does it? It just exports a promise interface.

**Comment by unional** [comment]
I recall it will either interop or polyfill Promise. Maybe I'm wrong.

**Comment by blakeembrey** [comment]
I don't believe it polyfills. In any case, I wouldn't do ambient. Let the user type their global promise implementation.

**Comment by unional** [comment]
Ok
