### ISSUE TITLE
extend type define of NodeJS.Process.env

### ISSUE THREAD

**Issue by GongT** [typings/registry#770]
installed: `registry:dt/node#6.0.0+20160907103612`

current content:
```ts
 export interface Process extends EventEmitter {
/// ....
    env: any;
/// ....
}
```

may change to:
```ts
export interface EnvironmentVariables {
    [key: string]: string;
}
export interface Process extends EventEmitter {
/// ....
    env: NodeJS.EnvironmentVariables;
/// ....
}
```

then users can extend `env` in their own .d.ts:
```ts
declare namespace NodeJS {
	export interface EnvironmentVariables {
		SOME_THING: string;
		SOME_OTHER_THING: string;
	}
}
```

currently this will cause `error TS2403: Subsequent variable declarations must have the same type.  Variable 'env' must be of type 'any', but here has type 'IProcessEnv'`:
```ts
interface IProcessEnv {
	SOME_THING: string;
	SOME_OTHER_THING: string;
}
declare namespace NodeJS {
	export interface Process {
		env: IProcessEnv;
	}
}
```

**Comment by felixfbecker** [comment]
You should open this at https://github.com/types/env-node

I also think this should be an index signature because all env vars are `string`, not `any`. But this will be a breaking change (even though it can be fixed with a regexp search/replace).
