### ISSUE TITLE
Typings for mysql2

### ISSUE THREAD

**Issue by felixfbecker** [typings/registry#778]
Since it's API compatible with mysql:

``` ts
export * from 'mysql'
```

`+` `execute` methods for prepared statements
`+` Promise wrapper `mysql2/promise`

**Comment by elaith9** [comment]
Can anyone explain how can I use mysql type definition with mysql2?

**Comment by felixfbecker** [comment]
Typings for `mysql2` are already available, run `typings install mysql2`
