### ISSUE TITLE
Relationship to DefinitelyTyped/DefinitelyTyped

### ISSUE THREAD

**Issue by zeke** [typings/registry#819]
:wave:

Newcomer to TypeScript land here.

What are the similarities and differences between this repo and https://github.com/DefinitelyTyped/DefinitelyTyped?

Do they have the same aim? Do they work in conjunction? Is one a fork of another?

**Comment by blakeembrey** [comment]
You can probably read through issues in https://github.com/typings/typings - such as https://github.com/typings/typings/issues/639. Here's one of my first posts on the topic - https://github.com/typings/typings/issues/72.
