### ISSUE TITLE
How to convert typed file with multiple entry points (module subpaths)

### ISSUE THREAD

**Issue by unional** [typings/registry#83]
e.g. `core-js` or `material-ui`

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7590f7725e5af7191a075700a70e4408b4f9cd45/core-js/core-js.d.ts#L1487-L1494

**Comment by blakeembrey** [comment]
Currently not possible, but there'll be support for `files` array soon. See https://github.com/typings/typings/issues/108.

**Comment by unional** [comment]
In the same light, need to wait for `files` support in order to write `nodejs` ambient module?
It exposes multiple non-subpath modules: `fs` `path` `stream` `child_process` etc.

**Comment by blakeembrey** [comment]
The node definition is different. It's an ambient collection that exposes a bunch of dependencies, not files. Files are internal to the module (E.g. `node/fs`), whereas what we want is just `node` providing `fs`. I think it's possibly today with very little tweaking (just needs someone to type it, and I think we can easily make it work by having `ambient` install dependencies without a namespace change.

**Comment by unional** [comment]
Actually, kind of a funny question: since node is ambient to begin with, aren't just copy what's in DT would work?

**Comment by blakeembrey** [comment]
@unional Yes, absolutely. In an ideal world, we can split it out a bit more to allow people to import specific pieces - E.g. Browserify, Webpack, etc. Anyway, yes.

**Comment by blakeembrey** [comment]
Closing in favour of https://github.com/typings/typings/issues/108
