### ISSUE TITLE
Compile a list of example repo

### ISSUE THREAD

**Issue by unional** [typings/registry#88]
For each common module shape:
* one function (e.g. `domready`)
* immutable utility (e.g. `lodash`)
* utility + function (e.g. `jquery`)
* utility + class (e.g. `bluebird`), identical to class with static?
* multiple subpath modules (e.g. `core-js`, `material-ui`, `ext-js`)
* sub-modules (e.g. `node`), any better name?

All suggestion welcome!

This will be added as `docs/examples.md` later.

**Comment by blakeembrey** [comment]
LGTM. Would you mind putting the examples in the primary repo and we can link across to them from the registry?

**Comment by unional** [comment]
Will do

**Comment by blakeembrey** [comment]
Closed with https://github.com/typings/typings/blob/master/docs/examples.md? Feel free to reopen if this isn't resolved.
