### ISSUE TITLE
passport-local not found in the registry

### ISSUE THREAD

**Issue by ehartford** [typings/registry#942]
if I type 'npm install @types/passport-local' it works 

but when I type 'typings install --save passport-local' it doesn't work.

    λ typings install --save passport-local
    typings ERR! message Unable to find "passport-local" ("npm") in the registry.

**Comment by unional** [comment]
Yes, because `@types` is from DT and not `typings/registry`.
As `npm install @types/passport-local` works, continue uses it.

Is there a reason you need to go the `typings` route?

**Comment by ehartford** [comment]
ok I was unaware that I can mix them.  Thank you.
