### ISSUE TITLE
angular-translate $translate.use() return type should be ng.IPromise<string>

### ISSUE THREAD

**Issue by rcollette** [typings/registry#966]
The return type of angular-translate `$translate.use()` is `ng.IPromise<string>` but currently the definition file has the return type defined as `string`.

**Comment by felixfbecker** [comment]
@rcollette you should open this issue at the appropiate reporitory that contains the definitions.

**Comment by rcollette** [comment]
Scratch that.  This was all confusion because someone in our environment had coded a test stub incorrectly, returning a promise in all cases.  Sorry for the confusion.  Closing.
