### ISSUE TITLE
Typing for stats.js do not work. I found a possible replacement.

### ISSUE THREAD

**Issue by Driky** [typings/registry#981]
The current definition file you get for the lib not work.

 ̶T̶h̶i̶s̶ ̶o̶n̶e̶ ̶d̶o̶e̶s̶
̶h̶t̶t̶p̶s̶:̶/̶/̶g̶i̶t̶h̶u̶b̶.̶c̶o̶m̶/̶J̶e̶f̶f̶J̶a̶n̶k̶o̶w̶s̶k̶i̶/̶s̶t̶a̶t̶s̶.̶t̶s̶

edit : My bad it doesn't.

**Comment by unional** [comment]
Are you referring to the typings in DefinitelyTyped? Can't fine stat.js here.

**Comment by Driky** [comment]
My apology I misspelled the name of the lib. It is stats.js
https://github.com/mrdoob/stats.js/

**Comment by unional** [comment]
Still can't find it. You install with `typings install dt~stats.js --global`? That' would be DefinitelyTyped.

Also, if found it here, will still redirect to the typings repo that actually have the typings written.

**Comment by Driky** [comment]
I install using `typings install stats.js --source dt --global`

**Comment by unional** [comment]
`--source dt` is the same as `dt~*`. Please raise this issue at DT.
